/**
 * Drop-in instruction files users download and add to their own repositories so
 * that ANY AI coding agent — Claude Code, OpenAI Codex, Cursor, Gemini, Windsurf,
 * Cline, Aider, or any MCP host — knows to call TokenItDown whenever it's handed a
 * file or URL. The files are generated per-instance so they carry this deployment's
 * hosted MCP endpoint and dashboard URL.
 *
 * - AGENTS.md  — the cross-agent standard (Codex, Cursor, many others read this).
 * - CLAUDE.md  — Claude Code's project memory file.
 * - skills.md  — a skill-style description for skill/MCP-host runners.
 */

export interface AgentFileContext {
  /** This instance's dashboard origin, e.g. https://tokenitdown.example.com */
  origin: string
  /** This instance's hosted MCP endpoint, e.g. https://…:8001/mcp */
  mcpUrl: string
}

export interface AgentFile {
  filename: string
  /** Short label for the dashboard. */
  title: string
  /** One-line description for the dashboard. */
  description: string
  content: string
}

const TOOLS_BLOCK = `## Tools

- \`convert_url_to_markdown(url)\` — fetch a web page or online document (article,
  docs page, Wikipedia, YouTube transcript, or a link to a PDF/Office file) and
  return clean Markdown. Prefer this over fetching the URL yourself.
- \`convert_file_to_markdown(path)\` — convert a local file on disk (PDF, Word,
  PowerPoint, Excel/CSV, images, audio, EPUB, JSON, ZIP, Outlook .msg, …) to
  Markdown. (Available when TokenItDown runs locally over stdio.)
- \`convert_document(content_base64, filename)\` — convert an uploaded file's bytes
  to Markdown. (Available on the hosted HTTP endpoint.)

The returned Markdown is already cleaned and token-efficient — cheaper and more
accurate to reason over than raw bytes or HTML.`

function whenToUse(): string {
  return `## When to use TokenItDown

Call a TokenItDown tool whenever the user references a document or web page you need
to **read, summarize, quote, search, compare, or extract from** — for example:

- "summarize this PDF", "what does report.docx say about X"
- "read https://… and …", "pull the key points from this page"
- any binary/office file or URL where you'd otherwise guess or paste raw HTML

Do **not** guess a binary file's contents from its name, and do **not** paste raw
HTML into context — convert it first.`
}

function localSetup(): string {
  return `### Local (stdio) — converts your own files, no account

\`\`\`bash
claude mcp add tokenitdown -- python -m app.mcp_server   # Claude Code
\`\`\`

Cursor (\`~/.cursor/mcp.json\`) / Claude Desktop:

\`\`\`json
{ "mcpServers": { "tokenitdown": { "command": "python", "args": ["-m", "app.mcp_server"] } } }
\`\`\`

VS Code (\`.vscode/mcp.json\`, note the \`servers\` key):

\`\`\`json
{ "servers": { "tokenitdown": { "type": "stdio", "command": "python", "args": ["-m", "app.mcp_server"] } } }
\`\`\``
}

function hostedSetup(ctx: AgentFileContext): string {
  return `### Hosted (HTTP) — for agents on any machine

Create an API key at ${ctx.origin}/dashboard/connect, then:

\`\`\`bash
claude mcp add --transport http tokenitdown ${ctx.mcpUrl} \\
  --header "Authorization: Bearer YOUR_TOKENITDOWN_API_KEY"
\`\`\`

For other hosts, point them at \`${ctx.mcpUrl}\` with an
\`Authorization: Bearer YOUR_TOKENITDOWN_API_KEY\` header. Every conversion you make
with a key is tracked in the dashboard (calls, tokens saved, and what was
converted).`
}

function agentsMd(ctx: AgentFileContext): string {
  return `# Agent instructions

> Drop this file in your repo root. AGENTS.md is read by Codex, Cursor, and most
> MCP-aware agents. (Claude Code reads CLAUDE.md — same guidance.)

This project uses **TokenItDown** to turn documents and web pages into clean,
LLM-ready Markdown. It is exposed to you over the Model Context Protocol (MCP).

${whenToUse()}

${TOOLS_BLOCK}

## Setup

${localSetup()}

${hostedSetup(ctx)}

---
Generated by TokenItDown · ${ctx.origin}
`
}

function claudeMd(ctx: AgentFileContext): string {
  return `# CLAUDE.md

Guidance for Claude Code working in this repository.

## TokenItDown — documents & web pages → Markdown

This project has the **TokenItDown** MCP server available. Use it as your default
way to read non-text sources.

${whenToUse()}

${TOOLS_BLOCK}

## Setup

${localSetup()}

${hostedSetup(ctx)}

---
Generated by TokenItDown · ${ctx.origin}
`
}

function skillsMd(ctx: AgentFileContext): string {
  return `# skills.md — TokenItDown

A skill your agent can call to convert any document or web page into clean,
LLM-ready Markdown. Point any MCP host or CLI at this file.

## Skill: convert-to-markdown

**What it does:** turns a file (PDF, Word, PowerPoint, Excel/CSV, image, audio,
EPUB, ZIP, …) or a URL/web page into cleaned Markdown that is cheaper and more
accurate for an LLM to reason over than raw bytes or HTML.

**When to load it:** whenever the user gives you a document or link to read,
summarize, quote, search, or extract from.

${TOOLS_BLOCK}

## Connect

${localSetup()}

${hostedSetup(ctx)}

---
Open source · Generated by TokenItDown · ${ctx.origin}
`
}

const BUILDERS: Record<string, { title: string; description: string; build: (ctx: AgentFileContext) => string }> = {
  "AGENTS.md": {
    title: "AGENTS.md",
    description: "Cross-agent standard — Codex, Cursor, Gemini, Windsurf, and most MCP hosts.",
    build: agentsMd,
  },
  "CLAUDE.md": {
    title: "CLAUDE.md",
    description: "Claude Code project memory — loaded at the start of every session.",
    build: claudeMd,
  },
  "skills.md": {
    title: "skills.md",
    description: "Skill-style description for skill runners and MCP hosts.",
    build: skillsMd,
  },
}

/** Names of the available downloadable files, for the dashboard listing. */
export function agentFileList(): { name: string; title: string; description: string }[] {
  return Object.entries(BUILDERS).map(([name, v]) => ({ name, title: v.title, description: v.description }))
}

/** Build one file's content, or null for an unknown name. */
export function buildAgentFile(name: string, ctx: AgentFileContext): AgentFile | null {
  const b = BUILDERS[name]
  if (!b) return null
  return { filename: name, title: b.title, description: b.description, content: b.build(ctx) }
}
